/* write a program to swap any two number :-
1: using third variable.
2: without third variable
*/

#include<iostream.h>
#include<conio.h>
void main(){
clrscr();

int a=10;
int b=20;
//int c;
cout<<"Before Swap"<<endl;
cout<<"A:-" <<a<<endl;
cout<<"B:-" <<b <<endl;

a=a+b;
b=a-b;
a=a-b;


cout<<"After Swap"<<endl;
cout<<"A:-" <<a<<endl;
cout<<"B:-" <<b <<endl;









getch();
}














